# Import

In [1]:
import torch

# Tensors

A tensor is a number, vector, matrix, or any n-dimensional array.

In [2]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [5]:
# Matrix
t3 = torch.tensor([[5., 6.],[7., 8,], [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
print(t1.shape)

torch.Size([])


In [7]:
print(t2.shape)

torch.Size([4])


In [8]:
print(t3.shape)

torch.Size([3, 2])


# Tensor operations and gradients

In [9]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [10]:
# Arithmatics operation
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

y is equal to 17. Pytorch automatically compute the derivative of y with respect to the tensors that have require_grad=True. i.e. w and b.

- This feature is called autograd(automatic gradients).

To compute the derivative using .backward on y.

In [11]:
# Compute derivatives
y.backward()

The derivatives of y w.r.t. the input tensors are stored in the .grad

In [12]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw: ', w.grad)
print('dy/db: ', b.grad)

dy/dx: None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


x is None because x doesn't have requires_grad=True.

# Tensor functions

In [13]:
# Create a tensor with a fixed value for every element.
t6 = torch.full((3, 2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [14]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t3, t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [15]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [16]:
# Change the shape of the tensor
t9 = t8.reshape(3, 2, 2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

More operation:https://pytorch.org/docs/stable/torch.html

## Interoperability with Numpy

[Numpy](http://www.numpy.org/) is a popular open-source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays and has a vast ecosystem of supporting libraries, including:

* [Pandas](https://pandas.pydata.org/) for file I/O and data analysis
* [Matplotlib](https://matplotlib.org/) for plotting and visualization
* [OpenCV](https://opencv.org/) for image and video processing


If you're interested in learning more about Numpy and other data science libraries in Python, check out this tutorial series: https://jovian.ai/aakashns/python-numerical-computing-with-numpy .

Instead of reinventing the wheel, PyTorch interoperates well with Numpy to leverage its existing ecosystem of tools and libraries.

In [17]:
import numpy as np

x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [18]:
# We can convert np to tensor
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [19]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)

In [20]:
# Convert tensor to np
z = y.numpy()
z

array([[1, 2],
       [3, 4]])